# Generated by Django 5.2.3 on 2025-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('amenagement', 'Aménagement'), ('environnement', 'Environnement'), ('transport', 'Transport'), ('social', 'Social')]),
        ),
        migrations.AlterField(
            model_name='idea',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='idea',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposée'), ('under_review', "En cours d'examen"), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('implemented', 'Implémentée')], default='proposed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
